# Generated by Django 3.1.5 on 2026-04-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0011_dayofweek_integer_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_prescription',
            name='follow_up_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='health_center.all_prescription'),
        ),
    ]
