# Generated by Django 3.1.5 on 2026-04-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_moduleaccess_database'),
        ('health_center', '0012_all_prescription_follow_up_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MedicalRelief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_relief/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PHC_REVIEWED', 'PHC Reviewed'), ('ACCOUNTS_REVIEWED', 'Accounts Reviewed'), ('SANCTIONED', 'Sanctioned'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='SUBMITTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_relief_reviewed', to='globals.extrainfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_relief_requests', to='globals.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('ann_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='globals.extrainfo')),
            ],
        ),
    ]
