# Generated by Copilot on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_center", "0013_auto_20260406_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="gender",
            field=models.CharField(blank=True, choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="blood_type",
            field=models.CharField(blank=True, choices=[("A+", "A+"), ("A-", "A-"), ("B+", "B+"), ("B-", "B-"), ("AB+", "AB+"), ("AB-", "AB-"), ("O+", "O+"), ("O-", "O-")], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="height",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="weight",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]